### ISSUE TITLE
Missing net.dryade.siri:siri-api:jar:1.0

### ISSUE THREAD

**Issue by Nhanhanha** [dryade/irys#1]
git clone the project, when I try running mvn test, il displays a build error
## Missing:

1) net.dryade.siri:siri-api:jar:1.0

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=net.dryade.siri -DartifactId=siri-api -Dversion=1.0 -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=net.dryade.siri -DartifactId=siri-api -Dversion=1.0 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
    1) irys:irys-common:jar:2.0.1
    2) net.dryade.siri:siri-api:jar:1.0

---

1 required artifact is missing.

for artifact: 
  irys:irys-common:jar:2.0.1

**Comment by metienne** [comment]
Irys has been moved here; https://github.com/afimb/irys
there is also a maven repository here : http://maven.chouette.mobi

**Comment by ldonnet** [comment]
We have updated the README to alert users to redirect to our new repository.
